language: node_js
node_js:
  - "0.12"
before_install:
  - "sudo pip install crossbar"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - npm install -g bower
  - bower install 
